### ISSUE TITLE
Undo/Redo on search line with Verify

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#10]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to go back to the original search line when trying to edit for a better match.  I think that tkinter allows undo/redo https://stackoverflow.com/questions/3169344/undo-and-redo-features-in-a-tkinter-text-widget

Which seems like a reasonable way to support this.

**Comment by corb555** [comment]
This should already be supported.  if you click on the user entry window, you should be able to type, or delete and then use Ctl-Z to undo and Ctl-Y to redo.  I just retested this and can;t reproduce the problem.  I've added logging to help diagnose.  With 0.8.9 you should see "UNDO xxx" show up in the log every time you press Ctrl-Z, and REDO for Ctl-Y.

**Comment by prculley** [comment]
You are right, it is there, sort of.  I selected a couple of words and cut them as a way to get a better match, then hit verify.
Then selected inside the entry widget again and hit ctrl-z a several times before looking, which I thought would have brought me back to the original setting.  Instead it left me with a blank entry.  Hitting ctrl-y to redo left me with a blank entry as well, so I thought it wasn't working.
Seem I have to hit ctrl-y again to get the entry back.

I guess the initial state is empty, and you can return to that, which is not exactly intuitive.  Don't know if this is tkinter or what....

Haven't tried 0.8.9 yet.

**Comment by corb555** [comment]
the initial state is blank which is very unintuitive.  That should be easy to change.

**Comment by corb555** [comment]
v0.9.0 is now published.  Undo now stops before going to blank initial state
