### ISSUE TITLE
Cannot change config and say yes to rebuild (Windows)

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#11]
**Describe the bug**
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.6\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\prc\workspace\Geofinder\GeoFinder\geofinder\UtilLayout.py", line 158, in quit_handler
    os.remove(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\prc\\geoname_data\\cache\\geodata.db'

**To Reproduce**
1. Enter config
2. Change a config value that suggest a db rebuild (I used the Features list to add 'PO' for post office)
3. Quit, and say yes to "Configuration Changed" message.

You cannot quit and ask for change, ends up back in config dialog.  You can say not to change, and quit.  But db won't be rebuilt.

I think this is another case where the db has to be closed to delete it.
I deleted it manually to make progress.

OS: WIN10

**Comment by corb555** [comment]
Fixed in 0.9.1
