### ISSUE TITLE
Can we have a Prefix, County, state, country?

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#12]
**Is your feature request related to a problem? Please describe.**
I have some places that are located in the county, not a city,  for example 
"325 CR45, xyz county, ohio, usa"  (CR stands for county road)

While the "325 CR45" ends up described as a prefix, there are no results that just include the county, they all seem to be trying to treat the county position as a city.

**Describe the solution you'd like**
When the front place in a full string like this occurs, but is not found, put at least some effort into finding the latter three as county, state, country, with the prefix described as the leading element.

**Comment by corb555** [comment]
This seems to work with  version 0.9.1. 
 `12 main street, boise, ,idaho` 
shows results for both the city and the county
