### ISSUE TITLE
Confused by Quit button in config

### ISSUE THREAD

**Issue by ennoborg** [corb555/GeoFinder#2]
When I add places, I am easily confused by the use of the Quit button. If it does what the manual says, meaning to save the configuration, I would expect it be called Save, and to either close the window, or to provide some feedback that my settings were saved, and I can close the window with the X in the upper right corner. Right now, I don't see that type of feedback.
Moreover, if I were to click that X after changing things, I would expect to see a warning, so that I can still save things.

**Comment by corb555** [comment]
A) Agreed the behavior of the Quit button was overloaded.  In v0.4, it now displays a prompt asking whether to create an output file or quit immediately.
B) v.04 intercepts the 'X' close widget and treats it as Quit.
