### ISSUE TITLE
Configurable path to the geonames file, and where geonames create its database.

### ISSUE THREAD

**Issue by StoltHD** [corb555/GeoFinder#3]
Great initiative, and it look promising, but...
On Windows at least, its important to be able to chose where to store data when it is as large as files as the geonames file.
Same with the database store, its important that its possible to create your own "database folder".

i.e.
I don't use C:\ for anything but OS and software files/config files... I have separate disks/SSD's for different type of content...

**Comment by corb555** [comment]
This makes sense.  Many systems now (including mine) have relatively small SSD drives along with a large application drive.  I am starting work on implementing adding a --path switch.  Unfortunately the Python directory create function is not creating the directory but is reporting success if the directory is outside the Home directory.  I'm trying to track down how to get around that.

**Comment by StoltHD** [comment]
@corb555 
I don't nkow what you use in your program, but I think you can use tkinter for this in Python... (ps. I don't know much about this so...) 
https://pythonspot.com/tk-file-dialogs/

It might be you need to import "os" to
https://docs.python.org/3/library/os.html

**Comment by corb555** [comment]
As of v.0.8.3, geofinder now reads the data path from geofinder.ini in the user's Home directory.  To change the path:  shutdown geofinder.  move the geonames_data folder to the desired location.  Update geofinder.ini to have the new path.  v0.8.3 also has a dialog for editting the INI file but it requires some additional changes.
