### ISSUE TITLE
Startup crashes on 0.8

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#6]
**Describe the bug**
Ran it a couple of times and got slightly different bugs...
**To Reproduce**
Started with "python3 geofinder.py"
C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>python3 geofinder.py
GeoFinder v0.8.0
Python 3.6
GeoFinder Requires Python 3.6 or higher
INFO __main__.setup_logging 797: geofinder Init
Traceback (most recent call last):
  File "geofinder.py", line 949, in <module>
    entry()
  File "geofinder.py", line 945, in entry
    GeoFinder()
  File "geofinder.py", line 158, in __init__
    self.ini_set(section='PATH', key='DIRECTORY', val=self.directory)
  File "geofinder.py", line 82, in ini_set
    self.ini.set(section, key, val)
  File "C:\msys64\mingw64\lib\python3.6\configparser.py", line 1192, in set
    self._validate_value_types(option=option, value=value)
  File "C:\msys64\mingw64\lib\python3.6\configparser.py", line 1177, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>python3 geofinder.py
GeoFinder v0.8.0
Python 3.6
GeoFinder Requires Python 3.6 or higher
INFO __main__.setup_logging 797: geofinder Init
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.6\configparser.py", line 789, in get
    value = d[option]
  File "C:\msys64\mingw64\lib\python3.6\collections\__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\msys64\mingw64\lib\python3.6\collections\__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'directory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "geofinder.py", line 949, in <module>
    entry()
  File "geofinder.py", line 945, in entry
    GeoFinder()
  File "geofinder.py", line 153, in __init__
    self.directory = Path(self.ini_read('PATH', 'DIRECTORY'))
  File "geofinder.py", line 78, in ini_read
    return self.ini.get(section, key)
  File "C:\msys64\mingw64\lib\python3.6\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'directory' in section: 'PATH'

**Desktop (please complete the following information):**
 - OS: Win10
Msys2/Mingw64 environment (older, not recently updated versions with Python3.6)

**Comment by prculley** [comment]
The c:\users\prc\.geofinder.ini file contains only "[PATH]" after the two runs.

**Comment by prculley** [comment]
Looks like you cannot use Path (WindowsPath in my case) objects as ordinary path strings.  Gonna have to use str() in a bunch of places or something...

**Comment by prculley** [comment]
I patched around the above issue and deleted my geofinder.ini file.  Then got another bug.

GeoFinder v0.8.0
Python 3.6
GeoFinder Requires Python 3.6 or higher 
INFO __main__.setup_logging 797: geofinder Init
INFO __main__.__init__ 170: Cache directory C:\Users\prc\geoname_data\cache
DEBUG __main__.check_configuration 905: load country selections list
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=country_list.pkl len=6
INFO __main__.check_configuration 920: Found C:\Users\prc\geoname_data\cache\geodata.db
DEBUG geofinder.Config.read 57: config read C:\Users\prc\geoname_data\cache config.pkl
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=config.pkl len=1
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=skiplist.pkl len=11
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=global_replace.pkl len=7
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=feature_list.pkl len=37
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=country_list.pkl len=6
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=languages_list.pkl len=1
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=output_list.pkl len=1
DEBUG geofinder.GeodataFiles.__init__ 94: Output replace []
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=feature_list.pkl len=37
DEBUG geofinder.CachedDictionary.read 53: Read success CachedDict dir=C:\Users\prc\geoname_data\cache fname=country_list.pkl len=6
DEBUG geofinder.GeodataFiles.read 122: done loading geodata
INFO __main__.load_data 248: 6 countries will be loaded
DEBUG geofinder.GeodataFiles.read_geoname 137: path for geodata.db: C:\Users\prc\geoname_data\cache\geodata.db
DEBUG geofinder.GeodataFiles.read_geoname 143: DB found at C:\Users\prc\geoname_data\cache\geodata.db
INFO geofinder.DB.connect 61: DB C:\Users\prc\geoname_data\cache\geodata.db connected
DEBUG geofinder.DB.db_test 199: db test sql=SELECT name FROM main.geodata WHERE name = ? AND country = ?   args=[('ba', 'fr')]
DEBUG geofinder.DB.db_test 203: DB no error
INFO geofinder.DB.set_speed_pragmas 245: Database pragmas set for speed
DEBUG geofinder.DB.table_exists 177: version sql=SELECT name FROM sqlite_master WHERE type=? AND name=?  LIMIT 105 args=[('table', 'version')]
DEBUG geofinder.DB.table_exists 181: DB version tbl: []
DEBUG geofinder.DB.table_exists 186: version table NOT FOUND
DEBUG geofinder.GeoDB.get_db_version 813: No version table.  Version is 1
DEBUG geofinder.GeodataFiles.read_geoname 182: Database version will be upgraded:

Adding support for non-English output

Upgrading database from V1 to V2.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.6\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\GeoFinder.py", line 268, in load_handler
    self.load_data()
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\GeoFinder.py", line 251, in load_data
    error = self.geodata.read_geonames()
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\Geodata.py", line 331, in read_geonames
    return self.geo_files.read_geoname()
  File "C:\msys64\mingw64\lib\python3.6\site-packages\geofinder\GeodataFiles.py", line 185, in read_geoname
    os.remove(db_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\prc\\geoname_data\\cache\\geodata.db'
INFO __main__.quit_handler 722: Shutdown
INFO geofinder.DB.set_analyze_pragma 254:  Database Analyze pragma
INFO geofinder.GeoDB.close 738: Closing Database
DEBUG geofinder.CachedDictionary.write 72: Write C:\Users\prc\geoname_data\cache\skiplist.pkl
DEBUG geofinder.CachedDictionary.write 72: Write C:\Users\prc\geoname_data\cache\global_replace.pkl
DEBUG geofinder.CachedDictionary.write 72: Write C:\Users\prc\geoname_data\cache\config.pkl
INFO __main__.shutdown 850: SYS EXIT

**Comment by prculley** [comment]
Inserted self.geodb.close() at line 185 of GeodataFiles to get around the last bug.

**Comment by prculley** [comment]
My patches to GeoFinder.py:
<pre>        self.ini = ConfigParser()
        self.ini_path = os.path.join(home_path, 'geofinder.ini')  #******

        if os.path.isfile(self.ini_path):  #******
            self.directory = Path(self.ini_read('PATH', 'DIRECTORY'))
        else:
            # Not Found.  Create INI file
            self.ini_add_section('PATH')
            self.directory = Path(os.path.join(home_path, GeoKeys.get_directory_name()))
            self.ini_set(section='PATH', key='DIRECTORY', val=str(self.directory))  #******</pre>

**Comment by prculley** [comment]
Will need more patching to get around failure if someone has tried 0.8 like I did and left geofinder.ini in partial setup state; I just deleted mine to make progress.

**Comment by corb555** [comment]
thanks for all the details!  I've put in more bullet-proofing into the INI section and pulled that out to a separate class (ini_handler.py).  On Windows it's still hanging at startup when it tries to build the DB, so looking into that now.  I've also added the geodb close statement you pointed out.  My Windows PC is in an unheated room which unfortunately has caused me to do minimal Windows testing.  It's always interesting how bugs can work fine on one OS and be caught by another.  Thanks again for all your help!

**Comment by corb555** [comment]
This should be fixed with v0.8.3.  Let me know if it is resolved and I will close.
