### ISSUE TITLE
0.8.4 pip issues.

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#7]
**Describe the bug**
I have no idea what is going on here.  0.8.4 won't install.  I tried to install 0.8.2 and 0.8.3, they both installed fine.  There is something weird happening with the path names; looks like it stuttered on build/lib.  If it is doing that for real, the path is possibly getting too long for Windows (256 chars max).  Session log attached.

It would be helpful if there was a version # somewhere in the GUI to see what was actually running...

C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>pip3 install geofinder --upgrade
Collecting geofinder
  Using cached https://files.pythonhosted.org/packages/4b/d9/82775cbe139ed86a3f4833a986f6bb89c7f12ff88150d1b0b09a4425e33b/geofinder-0.8.4-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\prc\\AppData\\Local\\Temp\\pip-install-y7xqzjfg\\geofinder\\build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/geofinder/AlternateNames.py'

C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>pip3 install geofinder==0.8.2
Collecting geofinder==0.8.2
  Downloading https://files.pythonhosted.org/packages/f3/1c/d2172eefdc9c491ade79f258515b211456ace71e76b1723ad2afc570d2fb/geofinder-0.8.2-py3-none-any.whl (2.3MB)
     |████████████████████████████████| 2.3MB 2.2MB/s
Requirement already satisfied: unidecode in c:\msys64\mingw64\lib\python3.6\site-packages (from geofinder==0.8.2) (1.1.1)
Requirement already satisfied: phonetics in c:\msys64\mingw64\lib\python3.6\site-packages (from geofinder==0.8.2) (1.0.5)
Installing collected packages: geofinder
  Found existing installation: geofinder 0.8.0
    Uninstalling geofinder-0.8.0:
Successfully installed geofinder-0.8.2

C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>pip3 install geofinder==0.8.3
Collecting geofinder==0.8.3
  Downloading https://files.pythonhosted.org/packages/8d/d3/7727982c89ed20a5679cb37702e71db8f7003216c620de8cce7ce6c878bb/geofinder-0.8.3-py3-none-any.whl (2.4MB)
     |████████████████████████████████| 2.4MB 2.2MB/s
Requirement already satisfied: unidecode in c:\msys64\mingw64\lib\python3.6\site-packages (from geofinder==0.8.3) (1.1.1)
Requirement already satisfied: phonetics in c:\msys64\mingw64\lib\python3.6\site-packages (from geofinder==0.8.3) (1.0.5)
Installing collected packages: geofinder
  Found existing installation: geofinder 0.8.2
    Uninstalling geofinder-0.8.2:
Successfully installed geofinder-0.8.3

C:\msys64\mingw64\lib\python3.6\site-packages\geofinder>pip3 install geofinder==0.8.4
Collecting geofinder==0.8.4
  Using cached https://files.pythonhosted.org/packages/4b/d9/82775cbe139ed86a3f4833a986f6bb89c7f12ff88150d1b0b09a4425e33b/geofinder-0.8.4-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\prc\\AppData\\Local\\Temp\\pip-install-77k3we_b\\geofinder\\build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/build/lib/geofinder/AlternateNames.py'

Win10 Msys2/Mingw64 environment.

**Comment by corb555** [comment]
That’s quite a pathname.  No need for more info from you on this.  i’ll take a look.  I now have PyCharm IDE on both my Windows PC and Mac and I think there’s some weird interaction since they try to synch with each other.  I really like PyCharm but it does have some magic under the hood that can be tricky.

**Comment by corb555** [comment]
0.8.5 should fix this.  On each build, the build system is creating another build/lib under the build/lib folder.  For the short term I have cleared these out, until I figure out the root cause. (Issue is not at all related to PyCharm or Windows)
