### ISSUE TITLE
Column size on Windows not ideal

### ISSUE THREAD

**Issue by prculley** [corb555/GeoFinder#9]
**Describe the bug**
The column sizing of the Score and Type columns is not wide enough to display the title and in some cases the Type.

It may be because  my system doesn't have a Helvetica font, so chose an inappropriate font which displays larger.
Also, the font is really quite a bit larger than usual or necessary for my system which cuts off some the the items in the Location and Prefix columns.
![image](https://user-images.githubusercontent.com/18122203/68493971-282ea080-0213-11ea-803a-73f26fcc9864.png)
**Desktop (please complete the following information):**
 - OS: Win10

**Comment by corb555** [comment]
The next version will:
1. Increase Score and Type columns by 10 pixels
2. Decrease font sizes by 2 to the following:  Small = 10, Med = 12, Large=14 and Title=16.  In the image above: green text above is Large, the black is Med, the Gray is Small, the blue is Title.

**Comment by corb555** [comment]
This has been updated as above in 0.8.6.  Let me know if the font and columns look good.
